language: cpp
sudo: false

matrix:
  include:
    - os: linux      
      env:
        - TEST="Clang Check"
      install:
        - wget http://ringmesh.org/download/RINGMesh-master-Linux.tar.gz
        - tar xzf RINGMesh-master-Linux.tar.gz

      script:
        - mkdir build
        - cd build
        - CXX=clang++ CC=clang cmake -DRINGMesh_INSTALL_PREFIX:PATH=$TRAVIS_BUILD_DIR/RINGMesh-master-Linux ..
        - cd Debug
        - cmake --build . -- -j2
        - ctest --output-on-failure -j2
        
    - os: linux      
      env:
        - TEST="GCC Check"
      install:
        - wget http://ringmesh.org/download/RINGMesh-master-Linux.tar.gz
        - tar xzf RINGMesh-master-Linux.tar.gz

      script:
        - mkdir build
        - cd build
        - CXX=g++ CC=gcc cmake -DRINGMesh_INSTALL_PREFIX:PATH=$TRAVIS_BUILD_DIR/RINGMesh-master-Linux ..
        - cd Debug
        - cmake --build . -- -j2
        - ctest --output-on-failure -j2
        
    - os: osx
      if: branch = master
      env:
        - TEST="Clang Check"
      install:
        - wget http://ringmesh.org/download/RINGMesh-master-Darwin.tar.gz
        - tar xzf RINGMesh-master-Darwin.tar.gz

      script:
        - mkdir build
        - cd build
        - CXX=clang++ CC=clang cmake -DRINGMesh_INSTALL_PREFIX:PATH=$TRAVIS_BUILD_DIR/RINGMesh-master-Darwin ..
        - cd Debug
        - cmake --build . -- -j2
        - ctest --output-on-failure -j2
        
    - os: osx
      if: branch = master
      env:
        - TEST="Xcode Check"
      install:
        - wget http://ringmesh.org/download/RINGMesh-master-Darwin.tar.gz
        - tar xzf RINGMesh-master-Darwin.tar.gz

      script:
        - mkdir build
        - cd build
        - cmake -G Xcode -DRINGMesh_INSTALL_PREFIX:PATH=$TRAVIS_BUILD_DIR/RINGMesh-master-Darwin ..
        - cd Debug
        - cmake --build . --config Debug
        - cmake -E env CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --target RUN_TESTS --config Debug
