language: cpp
sudo: false

os: linux

install:
  - wget http://ringmesh.org/download/RINGMesh-master-Linux.tar.gz
  - tar xzf RINGMesh-master-Linux.tar.gz

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake -DRINGMesh_INSTALL_PREFIX:PATH=$TRAVIS_BUILD_DIR/RINGMesh-master-Linux ..
  - cd Debug
  - cmake --build . -- -j2
  - ctest --output-on-failure -j2
